# Generated by Django 5.2.5 on 2026-01-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('insight_type', models.CharField(default='general', help_text='e.g., motivation, adjustment, warning', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fitness Journey', max_length=200)),
                ('total_weeks', models.IntegerField(default=12)),
                ('current_week', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('workouts_completed', models.IntegerField(default=0)),
                ('workouts_target', models.IntegerField(default=5)),
                ('nutrition_score', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('overall_streak', models.IntegerField(default=0, help_text='Consecutive days')),
                ('success_rate', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('calories_burned', models.IntegerField(default=0)),
                ('calories_target', models.IntegerField(default=2000)),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bodyweight_target_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workout_minutes', models.IntegerField(default=0)),
                ('workout_minutes_target', models.IntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weekly Stats',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[('upper_body', 'Upper Body Strength'), ('lower_body', 'Lower Body Strength'), ('cardio', 'Cardio'), ('core', 'Core'), ('full_body', 'Full Body'), ('flexibility', 'Flexibility')], max_length=50)),
                ('day', models.IntegerField(help_text='Day number in the program')),
                ('description', models.TextField(blank=True)),
                ('exercises_count', models.IntegerField(default=8)),
                ('focus_area', models.CharField(blank=True, help_text='e.g., Chest & Back focus', max_length=200)),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('calories_burned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('protein_g', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('fat_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('protein_target_g', models.IntegerField(default=140)),
                ('calories_target', models.IntegerField(default=2200)),
                ('fat_target_g', models.IntegerField(default=70)),
                ('carbs_target_g', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
