# Generated by Django 5.2.5 on 2026-02-23 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bodyweightentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('achievement_type', models.CharField(choices=[('calorie_crusher', 'Calorie Crusher'), ('strength_master', 'Strength Master'), ('marathon_runner', 'Marathon Runner'), ('perfect_week', 'Perfect Week'), ('consistency_king', 'Consistency King'), ('early_bird', 'Early Bird')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('target_value', models.IntegerField(help_text='Target value to complete achievement (e.g., 1000 calories)')),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('bench_press', 'Bench Press'), ('squat', 'Squat'), ('deadlift', 'Deadlift'), ('pull_up', 'Pull Up'), ('overhead_press', 'Overhead Press'), ('barbell_row', 'Barbell Row')], max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.IntegerField(default=1, help_text='Number of reps for this weight')),
                ('achieved_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_date'],
                'unique_together': {('user', 'exercise_type')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
                ('month', models.DateField(help_text='Month for this achievement (first day of month)')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='dashboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'achievement__name'],
                'unique_together': {('user', 'achievement', 'month')},
            },
        ),
    ]
