# Generated by Django 5.2.5 on 2026-02-24 08:00

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_achievement_personalrecord_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achievement_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='target_value',
        ),
        migrations.AddField(
            model_name='achievement',
            name='total_earned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AchievementCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='achievement_carts')),
                ('title', models.CharField(choices=[('calorie crusher', 'Calorie Crusher'), ('strength master', 'Strength Master'), ('marathon runner', 'Marathon Runner'), ('perfect week', 'Perfect Week'), ('workout finisher', 'Workout Finisher'), ('active days', 'Active Days')], default='calorie crusher', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actual_value', models.IntegerField(blank=True, default=0, null=True)),
                ('target_value', models.IntegerField(blank=True, default=0, null=True)),
                ('current_month', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='dashboard.achievement')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalRecord',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
