# Generated by Django 5.2.5 on 2026-02-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_userachievement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementcarts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achievement Cart', 'verbose_name_plural': 'Achievement Cart'},
        ),
        migrations.RemoveField(
            model_name='achievementcarts',
            name='achievement',
        ),
    ]
