# Generated by Django 5.2.5 on 2026-02-25 04:15

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_achievementcarts_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='achievement_icon')),
                ('title', models.CharField(choices=[('calorie crusher', 'Calorie Crusher'), ('strength master', 'Strength Master'), ('marathon runner', 'Marathon Runner'), ('perfect week', 'Perfect Week'), ('workout finisher', 'Workout Finisher'), ('active days', 'Active Days')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('actual_value', models.IntegerField(blank=True, default=0, null=True)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.achievementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AchievementCarts',
        ),
    ]
