# Generated by Django 5.2.5 on 2026-02-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_achievementdefinition_userachievement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementdefinition',
            options={'ordering': ['order'], 'verbose_name': 'Achievement Input Definition', 'verbose_name_plural': 'Achievement Input Definitions'},
        ),
        migrations.AddField(
            model_name='userachievement',
            name='status',
            field=models.CharField(choices=[('earned', 'Earned'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievementdefinition',
            name='title',
            field=models.CharField(choices=[('calorie crusher', 'Calorie Crusher'), ('strength master', 'Strength Master'), ('marathon runner', 'Marathon Runner'), ('active days', 'Active Days'), ('workout finisher', 'Workout Finisher'), ('perfect week', 'Perfect Week')], max_length=100),
        ),
    ]
