# Generated by Django 5.2.5 on 2025-11-11 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class (e.g., 'fas fa-star')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Review Category',
                'verbose_name_plural': 'Review Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reviews', models.BooleanField(default=True, help_text='Enable/disable review submission')),
                ('require_approval', models.BooleanField(default=True, help_text='Require admin approval before displaying reviews')),
                ('allow_anonymous', models.BooleanField(default=True, help_text='Allow anonymous reviews without login')),
                ('show_title', models.CharField(default='Share Your Feedback', help_text='Form heading', max_length=255)),
                ('show_subtitle', models.CharField(default='Help us improve your experience', help_text='Form subheading', max_length=255)),
                ('placeholder_text', models.CharField(default="Share your thoughts, suggestions, or anything else you'd like us to know...", help_text='Placeholder text for feedback textarea', max_length=255)),
                ('submit_button_text', models.CharField(default='Submit Feedback', max_length=100)),
                ('min_rating', models.IntegerField(default=1)),
                ('max_rating', models.IntegerField(default=5)),
                ('min_text_length', models.IntegerField(default=10)),
                ('max_text_length', models.IntegerField(default=500)),
                ('notify_on_new_review', models.BooleanField(default=True, help_text='Send email to admin on new review')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address for notifications', max_length=254, null=True)),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Show review form on homepage')),
                ('reviews_per_page', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Settings',
                'verbose_name_plural': 'Review Settings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(help_text='User feedback, suggestions, or comments (max 500 characters)', max_length=500)),
                ('user_name', models.CharField(blank=True, help_text='Name for anonymous reviews', max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, help_text='Email for anonymous reviews', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval for displaying on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this review on homepage')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to users)', null=True)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to the review', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When admin responded', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the review (optional for anonymous reviews)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='review_revi_created_38db0b_idx'), models.Index(fields=['rating'], name='review_revi_rating_71640b_idx'), models.Index(fields=['is_approved'], name='review_revi_is_appr_139439_idx')],
            },
        ),
    ]
