# Generated by Django 5.2.5 on 2025-11-11 09:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(help_text='Support email address (e.g., support@example.com)', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('support_phone', models.CharField(help_text='Support phone number (e.g., +1 (123) 456-7890)', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('support_phone_display', models.CharField(blank=True, help_text='Formatted phone number for display (e.g., +1 (123) 456-7890)', max_length=30)),
                ('average_response_time', models.CharField(default='Under 2 hours', help_text="Average response time display text (e.g., 'Under 2 hours')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false to disable contact support section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Support',
                'verbose_name_plural': 'Contact Support',
                'db_table': 'contact_support',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Document title (e.g., 'Terms of Service')", max_length=200)),
                ('document_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('gdpr_compliance', 'GDPR Compliance'), ('disclaimer', 'Disclaimer'), ('refund_policy', 'Refund Policy'), ('other', 'Other')], help_text='Type of legal document', max_length=50, unique=True)),
                ('content', models.TextField(help_text='Full content of the legal document (supports HTML)')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', max_length=200, unique=True)),
                ('version', models.CharField(default='1.0', help_text='Document version number', max_length=20)),
                ('effective_date', models.DateField(help_text='Date when this version becomes effective')),
                ('is_active', models.BooleanField(default=True, help_text='Set to false to hide this document')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'db_table': 'legal_documents',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Auto-generated ticket number', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Contact email for ticket updates', max_length=254)),
                ('subject', models.CharField(help_text='Ticket subject/title', max_length=255)),
                ('message', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the ticket', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date and time when ticket was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the ticket (optional for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
