# Generated by Django 5.2.5 on 2025-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tips',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
