# Generated by Django 5.2.5 on 2025-12-08 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_exercisereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reps_completed', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('tough', 'Tough'), ('very_tough', 'Very Tough')], max_length=20)),
                ('target_hit', models.CharField(choices=[('not_at_all', 'Not at All'), ('slightly', 'Slightly'), ('moderately', 'Moderately'), ('well', 'Well'), ('very_well', 'Very Well')], max_length=20)),
                ('energy_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('body_feeling', models.CharField(choices=[('very_poor', 'Very Poor'), ('poor', 'Poor'), ('okay', 'Okay'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('satisfaction', models.CharField(choices=[('very_dissatisfied', 'Very Dissatisfied'), ('dissatisfied', 'Dissatisfied'), ('neutral', 'Neutral'), ('satisfied', 'Satisfied'), ('very_satisfied', 'Very Satisfied')], max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_reviews', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='task.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout Review',
                'verbose_name_plural': 'Workout Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('workout_plan', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ExerciseReview',
        ),
    ]
