# Generated by Django 5.2.5 on 2026-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_workoutreview_delete_exercisereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='tips',
            new_name='pro_tips',
        ),
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
