# Generated by Django 5.2.5 on 2026-01-29 11:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_tips_exercise_pro_tips_exercise_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='meal_photo'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(blank=True, default='My Workout Plan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
