# Generated by Django 5.2.5 on 2026-02-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_meal_photo_alter_dietplan_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
