# Generated by Django 5.2.5 on 2026-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_exercise_options_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('replaced', 'Replaced'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
