# Generated by Django 5.2.5 on 2026-02-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_meal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('hiit', 'HIIT'), ('core', 'Core'), ('full_body', 'Full Body')], max_length=100, null=True),
        ),
    ]
