# Generated by Django 5.2.5 on 2026-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_exercisechatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
