from django.db import models
from django.conf import settings
import uuid


class WorkoutPlan(models.Model):
    """Model to store workout plans generated by AI."""
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('paused', 'Paused'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='workout_plans'
    )
    chat_session = models.ForeignKey(
        'manageai.ChatSession',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workout_plans'
    )
    name = models.CharField(max_length=255, default='My Workout Plan')
    summary = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    start_date = models.DateField(auto_now_add=True)
    target_completion_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Workout Plan'
        verbose_name_plural = 'Workout Plans'
    
    def __str__(self):
        return f"{self.name} - {self.user.email}"
    
    @property
    def total_exercises(self):
        return self.exercises.count()
    
    @property
    def completed_exercises(self):
        return self.exercises.filter(status='completed').count()
    
    @property
    def progress_percentage(self):
        total = self.total_exercises
        if total == 0:
            return 0
        return round((self.completed_exercises / total) * 100, 2)


class Exercise(models.Model):
    """Model to store individual exercises within a workout plan."""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('skipped', 'Skipped'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workout_plan = models.ForeignKey(
        WorkoutPlan,
        on_delete=models.CASCADE,
        related_name='exercises'
    )
    name = models.CharField(max_length=255)
    sets = models.IntegerField(default=3)
    reps = models.CharField(max_length=50)  # Can be "10-12" or "30 seconds"
    description = models.TextField(blank=True, null=True)  # Detailed explanation of the exercise
    tips = models.JSONField(blank=True, null=True, default=list)  # Array of tips for the exercise
    completed_sets = models.IntegerField(default=0)
    notes = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    order = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['order', 'created_at']
        verbose_name = 'Exercise'
        verbose_name_plural = 'Exercises'
    
    def __str__(self):
        return f"{self.name} - {self.sets} sets x {self.reps}"
    
    @property
    def is_completed(self):
        return self.status == 'completed'
    
    @property
    def completion_percentage(self):
        if self.sets == 0:
            return 0
        return round((self.completed_sets / self.sets) * 100, 2)


class DietPlan(models.Model):
    """Model to store diet plans generated by AI."""
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('paused', 'Paused'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='diet_plans'
    )
    chat_session = models.ForeignKey(
        'manageai.ChatSession',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='diet_plans'
    )
    name = models.CharField(max_length=255, default='My Diet Plan')
    summary = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    start_date = models.DateField(auto_now_add=True)
    target_completion_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Diet Plan'
        verbose_name_plural = 'Diet Plans'
    
    def __str__(self):
        return f"{self.name} - {self.user.email}"
    
    @property
    def total_meals(self):
        return self.meals.count()
    
    @property
    def total_daily_calories(self):
        return sum(meal.calories for meal in self.meals.all())
    
    @property
    def total_daily_protein(self):
        return sum(meal.protein for meal in self.meals.all())
    
    @property
    def total_daily_carbs(self):
        return sum(meal.carbs for meal in self.meals.all())
    
    @property
    def total_daily_fats(self):
        return sum(meal.fats for meal in self.meals.all())


class Meal(models.Model):
    """Model to store individual meals within a diet plan."""
    MEAL_TYPE_CHOICES = [
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('snack', 'Snack'),
        ('dinner', 'Dinner'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('skipped', 'Skipped'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    diet_plan = models.ForeignKey(
        DietPlan,
        on_delete=models.CASCADE,
        related_name='meals'
    )
    meal_type = models.CharField(max_length=20, choices=MEAL_TYPE_CHOICES)
    title = models.CharField(max_length=255)
    items = models.JSONField()  # List of food items
    calories = models.IntegerField(default=0)
    protein = models.IntegerField(default=0)
    carbs = models.IntegerField(default=0)
    fats = models.IntegerField(default=0)
    notes = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    order = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['order', 'created_at']
        verbose_name = 'Meal'
        verbose_name_plural = 'Meals'
    
    def __str__(self):
        return f"{self.get_meal_type_display()} - {self.title}"
    
    @property
    def is_completed(self):
        return self.status == 'completed'


class DailyProgress(models.Model):
    """Model to track daily progress for workout and diet completion."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='daily_progress'
    )
    date = models.DateField()
    workout_plan = models.ForeignKey(
        WorkoutPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='daily_progress'
    )
    diet_plan = models.ForeignKey(
        DietPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='daily_progress'
    )
    exercises_completed = models.IntegerField(default=0)
    meals_completed = models.IntegerField(default=0)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-date']
        verbose_name = 'Daily Progress'
        verbose_name_plural = 'Daily Progress'
        unique_together = ['user', 'date']
    
    def __str__(self):
        return f"{self.user.email} - {self.date}"
