# Generated by Django 5.2.5 on 2025-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_verification_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verification_otp_expired',
            field=models.BooleanField(default=False),
        ),
    ]
