# Generated by Django 5.2.5 on 2025-11-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_check_verification_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check_verification_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verification_otp_expired',
        ),
    ]
