# Generated by Django 5.2.5 on 2025-12-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text="User's unique referral code to share with others", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code of the person who invited this user', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_referral_code', models.CharField(db_index=True, help_text='Referral code of the inviter', max_length=50)),
                ('child_email', models.EmailField(db_index=True, help_text='Email of the user who was referred', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('child_profile', models.ForeignKey(help_text='The profile who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='users.profile')),
                ('parent_profile', models.ForeignKey(blank=True, help_text='The profile who made the referral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='users.profile')),
            ],
            options={
                'verbose_name': 'User Referral',
                'verbose_name_plural': 'User Referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_referral_code'], name='users_userr_parent__ac1145_idx'), models.Index(fields=['child_email'], name='users_userr_child_e_b783ba_idx'), models.Index(fields=['-created_at'], name='users_userr_created_f070e6_idx')],
                'unique_together': {('parent_referral_code', 'child_email')},
            },
        ),
    ]
