# Generated by Django 5.2.5 on 2026-01-15 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Plan Session',
                'verbose_name_plural': 'AI Plan Sessions',
                'db_table': 'ai_plan_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPlanConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField(help_text="User's input/question")),
                ('ai_message', models.TextField(help_text="AI's response message")),
                ('summary', models.TextField(blank=True, help_text='Updated user profile summary', null=True)),
                ('workout', models.JSONField(blank=True, default=list, help_text='Workout plan data in JSON format')),
                ('diet', models.JSONField(blank=True, default=list, help_text='Diet plan data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_plan.aiplansession')),
            ],
            options={
                'verbose_name': 'AI Plan Conversation',
                'verbose_name_plural': 'AI Plan Conversations',
                'db_table': 'ai_plan_conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
