# Generated by Django 5.2.5 on 2025-11-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrelaunchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's full name", max_length=255)),
                ('email', models.EmailField(db_index=True, help_text="User's email address (must be unique)", max_length=254, unique=True)),
                ('referral_code', models.CharField(db_index=True, help_text="User's unique referral code to share with others", max_length=50, unique=True)),
                ('referred_by', models.CharField(blank=True, db_index=True, help_text='Referral code of the person who invited this user', max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for fraud detection', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent for fraud detection', null=True)),
                ('activated', models.BooleanField(default=False, help_text='Whether this user has activated their main account')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pre-Launch User',
                'verbose_name_plural': 'Pre-Launch Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='prelaunch_p_created_979bf7_idx'), models.Index(fields=['email'], name='prelaunch_p_email_04029c_idx'), models.Index(fields=['referral_code'], name='prelaunch_p_referra_1baa6c_idx'), models.Index(fields=['referred_by'], name='prelaunch_p_referre_45408c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrelaunchReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_referral_code', models.CharField(db_index=True, help_text='Referral code of the inviter', max_length=50)),
                ('child_email', models.EmailField(db_index=True, help_text='Email of the user who was referred', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('child_user', models.ForeignKey(help_text='The user who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='prelaunch.prelaunchuser')),
                ('parent_user', models.ForeignKey(blank=True, help_text='The user who made the referral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='prelaunch.prelaunchuser')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_referral_code'], name='prelaunch_p_parent__6e3bcb_idx'), models.Index(fields=['child_email'], name='prelaunch_p_child_e_c2e880_idx'), models.Index(fields=['-created_at'], name='prelaunch_p_created_a9f245_idx')],
                'unique_together': {('parent_referral_code', 'child_email')},
            },
        ),
    ]
