# Generated by Django 5.2.5 on 2025-12-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelaunchreferral',
            name='child_user',
            field=models.ForeignKey(blank=True, help_text='The user who was referred (null for main app users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='prelaunch.prelaunchuser'),
        ),
    ]
