# Generated by Django 5.2.5 on 2026-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('modification', 'Modification')], default='chat', max_length=20),
        ),
    ]
