# Generated by Django 5.2.5 on 2025-11-10 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICoachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='NEW FEATURE', help_text='Badge text above the heading', max_length=50)),
                ('heading', models.CharField(default='AI Personal Coach', max_length=255)),
                ('description', models.TextField(default='Get personalized guidance, motivation, and strategies tailored to your specific goals and challenges.')),
                ('button_text', models.CharField(default='Learn how it works', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_image', models.ImageField(blank=True, help_text='Preview image/screenshot of the AI coach interface', null=True, upload_to='cms/ai_coach/')),
                ('background_color', models.CharField(default='#000000', help_text='Background color in hex format', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Coach Section',
                'verbose_name_plural': 'AI Coach Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Create AI-powered solutions people genuinely want to use', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description text below the heading', null=True)),
                ('button_text', models.CharField(default='Start Free Trial', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(default='#000000', help_text='Background color in hex format', max_length=50)),
                ('button_color', models.CharField(default='#CCFF00', help_text='Button color in hex format', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/features/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color in hex format', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Section',
                'verbose_name_plural': 'Feature Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Icon for this goal', null=True, upload_to='cms/goals/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fitness Goal',
                'verbose_name_plural': 'Fitness Goals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('company', 'Company'), ('legal', 'Legal'), ('social', 'Social Media'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Icon class or image URL', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='What fitness goal do you need to achieve?', max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description text below the heading', null=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='cms/hero/')),
                ('status', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('threads', 'Threads'), ('other', 'Other')], max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Icon class or Font Awesome class', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStoriesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Success Stories', max_length=255)),
                ('sub_heading', models.TextField(default='Join thousands of others who have made their goals with 3rd+ months of personalized guidance, improved well-being!')),
                ('background_color', models.CharField(default='#000000', help_text='Background color in hex format', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Success Stories Section',
                'verbose_name_plural': 'Success Stories Sections',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='cms/testimonials/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('testimonial_text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='cms.successstoriessection')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CMS',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, help_text='Category for grouping FAQs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='hero_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cms.herosection'),
        ),
    ]
