# Generated by Django 5.2.5 on 2025-11-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_aicoachsection_ctasection_featuresection_fitnessgoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='STRENNO Fitness Platform', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🎯 Website Content Manager (ALL-IN-ONE)',
                'verbose_name_plural': '🎯 Website Content Manager (ALL-IN-ONE)',
            },
        ),
    ]
