# Generated by Django 5.2.5 on 2026-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_legaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='type',
            field=models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms and Conditions')], max_length=50, unique=True),
        ),
    ]
