# Generated by Django 5.2.5 on 2026-04-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_legaldocument_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
