# Generated by Django 5.2.5 on 2026-01-21 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as "Most Popular" plan')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Choose Your Plan', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Optional subtitle or description', null=True)),
                ('background_color', models.CharField(default='#1a1a1a', help_text='Hex color code', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=50)),
                ('popular_badge_text', models.CharField(default='Most Popular', max_length=50)),
                ('popular_badge_color', models.CharField(default='#d4ff00', help_text='Hex color code', max_length=50)),
                ('free_plan_button_text', models.CharField(default='Get Started Free', max_length=50)),
                ('paid_plan_button_text', models.CharField(default='Get Started', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Section',
                'verbose_name_plural': 'Pricing Section',
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['display_order', 'price']},
        ),
        migrations.AddField(
            model_name='package',
            name='border_color',
            field=models.CharField(default='#4a4a4a', help_text='Card border color (hex)', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='button_color',
            field=models.CharField(default='#d4ff00', help_text='Button background color (hex)', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='button_text_color',
            field=models.CharField(default='#000000', help_text='Button text color (hex)', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as "Most Popular" plan'),
        ),
        migrations.AddField(
            model_name='package',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='paypal_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g., "Perfect for trying out GoalAI"', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscription.package')),
            ],
            options={
                'ordering': ['order', 'feature_text'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscription.planitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
