# Generated by Django 5.2.5 on 2026-01-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_planitem_pricingsection_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['created_at']},
        ),
    ]
