# Generated by Django 5.2.5 on 2026-01-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_features_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['-created_at']},
        ),
    ]
