# Generated by Django 5.2.5 on 2026-01-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_features_options_alter_planitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['created_at']},
        ),
    ]
