# Generated by Django 5.2.5 on 2026-02-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_planitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['created_at']},
        ),
    ]
