# Generated by Django 5.2.5 on 2026-02-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_features_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='PlanItem',
        ),
    ]
