# Generated by Django 5.2.5 on 2026-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_delete_features_delete_planitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('free_trial', 'Free Trial')], default='stripe', max_length=20),
        ),
    ]
