# Generated by Django 5.2.5 on 2025-11-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('daily_checkin_reminders', models.BooleanField(default=True, help_text='Receive daily check-in reminder notifications')),
                ('milestone_achievements', models.BooleanField(default=True, help_text='Receive notifications about milestone achievements')),
                ('ai_insights_and_tips', models.BooleanField(default=True, help_text='Receive AI-generated insights and tips')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications on mobile/web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with these notification preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
